### ISSUE TITLE
Fails to start properly on Win64

### ISSUE THREAD

**Issue by step21** [piratechest/piratechest#12]
- no icon
- no window
- no ouptut on cmd
  spawns 1-3 processes according to taskmanager but no idea what it is doing :)

**Comment by d11e9** [comment]
Is that the prebuilt binary release or git clone and run locally?

**Comment by step21** [comment]
That is the prebuilt binary release.

**Comment by step21** [comment]
Mmh, so apparently it is the same from source. I cloned from github, did `npm install` in the main dir and /app and the run `npm run app`. This is the output:

```
> PirateChest@0.0.3 app C:\Users\Florian\piratechest
> nw ./app
```

Even after leaving it for a few minutes, there is no additional output/no error messages (and no window)

**Comment by step21** [comment]
Fixed in https://github.com/piratechest/piratechest/commit/b2fa9abaccbf4f83a61454d647604dc2a8ad4670
